---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: crypto-system
spec:
  interval: 5m
  releaseName: mongodb
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mongodb
      version: 10.6.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  # dependsOn:
  #   - name: sealed-secrets
  #     namespace: kube-system
  values:
    architecture: standalone
    auth:
      rootPassword: ''
      username: ''
      password: ''
      database: 'zenbot4'
    persistence:
      enabled: false
      #  existingClaim: "-"
      storageClass: ''
      accessModes:
        - ReadWriteOnce
      size: 8Gi
    #  mountPath: /bitnami/mongodb
