apiVersion: v1
kind: Service
metadata:
  name: zenbot
  namespace: crypto-system
spec:
  type: ClusterIP
  ports:
    - port: 17365
      targetPort: 17365
      protocol: TCP
      name: zenbot
  selector:
    app: zenbot
